services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - envirvars.env
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - envirvars.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=icelandic_aid_db
      - PGSSLMODE=allow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 